---
title: "Sistema Urbano Territorial"
description: |
  Desarrollo del trabajo de Investigación
author:
  - name: Federico Córdoba 
    url: https://blackfriedrich.github.io/spatialdataportal/blackfriedrich.html
    affiliation: OFUT-FAU-UNT
    affiliation_url: https://www.observatoriofau.com.ar/
date: "`r Sys.Date()`"
output: distill::distill_article
---

*"Las ciudades brindan oportunidades de aumentos de productividad y bienestar/inclusión en la medida que estas pueden generar un buen balance entre ganancias por economías de aglomeración y amenidades, por un lado, y pérdidas por costos de congestión, por el otro."*


## Introducción

El reconocimiento de las estructuras urbanas de los municipios en el Sistema Urbano Territorial de Tucumán da cuenta de los proceso asociados al crecimiento urbano, los usos del suelo, el desarrollo de amenidades (centralidades urbanas) y las infraestructuras de acceso a las mismas. 

La información recopilada y procesada sirve a un análisis territorial que busca evidenciar cómo las dinámicas productivas influyen en la estructura urbana de las urbanizaciones.

Los aportes de este trabajo en conjunto con otros, propios de los trabajos de las investigaciones vinculadas, contribuyen al desarrollo del conocimiento y el fortalecimiento de las capacidades de gestión local asociadas a la planificación urbana, a partir de la provisión de información que facilita el estudio y la comprensión del territorio.

Entre los aportes que se realizan para los trabajos de investigación pertinentes se encuentran:

- La recopilación de información de fuentes con datos abiertos.
- El procesamiento de información que sirva a la construcción de un atlas municipal.
- El desarrollo de técnicas que faciliten la adquisición, manipulación y visualización de la información.
- El desarrollo de abordajes conceptuales que de un marco a la comprensión y reflexion de los procesos que se investigan.

## Consideraciones Previas

### Suelo Urbano

Fracción del territorio que presentan condiciones propicias para el desarrollo de actividades urbanas: infraestructuras, servicios básicos, equipamientos, condiciones de aglomeración y diversidad de actividades.

### Estructura Urbana

Es la organización espacial de una ciudad, es decir, la forma en que se distribuyen y relacionan entre sí los diferentes elementos que la componen: la trama urbana, los usos del suelo, la densidad, la altura de los edificios, los espacios públicos y La infraestructuras.

Influye en muchos aspectos de la vida cotidiana, como ser:

- La movilidad: Cómo nos desplazamos de un lugar a otro.
- La accesibilidad: La facilidad con la que podemos llegar a los servicios y equipamientos.
- La calidad de vida: El ambiente en el que vivimos y trabajamos.
- El desarrollo económico: La ubicación de las actividades productivas.

### Sitema Territorial

Es el conjunto de elementos naturales, sociales, económicos y culturales que interactúan entre sí en un espacio geográfico determinado (unidad de análisis). Es una forma de entender el territorio como un sistema complejo y dinámico, donde todos los elementos están interconectados y se influyen mutuamente.

En el Sistema Urbano Territorial de Tucumán nos referimos a cómo los centros urbanos de la provincia se interrelacionan entre sí y con otros elementos territoriales que forman parte del sistema.

## Hipótesis

La forma de las ciudades y sus dinámicas de crecimiento pueden ser explicadas a partir de la comprensión de las dinámicas económicas subyacentes en la estructura urbana, organizadas entorno a uno o múltiples centros de mayor densidad (CBD*) y un borde de baja densidad, que se presenta como un límite cuando el valor de la tierra productiva agrícola es mayor al valor de la transformación de ese suelo a urbano.  

*CBD son las siglas en inglés de Central Business District, que en español se traduce como Distrito Central de Negocios. Es el corazón económico de una ciudad, el área donde se concentran las actividades comerciales, financieras y administrativas más importantes.

## Objetivos

Cómo objetivo principal se pretente la generación de una cartografía temática especializada por municipio, que permita la interpretación de los procesos urbanos a partir de sus elementos estructurantes.

Cómo objetivos específicos se encuentran, (1) El desarrollo de la técnica para la adquisición, limpieza y visualización de los datos; (2) La construcción de una base de datos con la información procesada y limpia; (3) La presentación de un Atlas preliminar, que nutra al proyecto de investigación de "Agenda Urbana" que cuenta con su propio atlas; (4) Una construcción teórica y metodológica para la comprensión de la tarea resuelta; (5) La articulación del presente trabajo con otros trabajos tanto de investigación como de práctica profesional.

## Metodología

A partir de las reflexiones en torno a la información requerida y disponible, y superados los desafíos técnicos que conlleva su adquisición y procesamiento, el proceso de toma de decisiones fue configurando la siguiente propuesta metodológica en torno a la construcción del presente proyecto.

Cómo punto de partida para en análisis de la información empezamos realizando las siguientes consideraciones:

### Selección de Información

Para la comprensión de la estructura urbana, en el abordaje de los temás propuestos se consideraron, para esta primera etapa:

Los límites jurisdiccionales: que determinan las unidades de análisis; 

Estructura Parcelaria: que da cuenta de los usos del suelo y los procesos de urbanización subyacentes.

Edificabilidad: correlativo a los usos del suelo, devela condiciones de densidad de ocupación y ociosidad del suelo, relativo a las formas de producción de suelo urbano, y condiciones del suelo: valorización, aptitud constructiva, normativas.

Estructura vial: conforma la trama de la ciudad: calles y manzanas, escenciales para permitir el acceso a bienes, servicios e infraestructuras de las funciones urbanas. 

Aménidades urbanas: reflejan las áreas de mayor valor, que canalizan los flujos y requieren condiciones especiales acceso.

### Selección de Fuentes

Se Optó por las siguientes fuentes:

Para límites jurisdiccionales: [Instituto de Geografía](https://www.filo.unt.edu.ar/ieg/?page_id=963)

Para el Parcelario: Catastro de Tucumán | [Geoservicios IDET](https://idet.tucuman.gob.ar/servicios_organismos/servicios_organismos/15/2)

Edificabilidad: [Google Open Buildings](https://sites.research.google/open-buildings/)

Estructura Vial: [Open street map](https://wiki.openstreetmap.org/wiki/Map_features)

Aménidades urbanas: [Open street map](https://wiki.openstreetmap.org/wiki/Map_features)

### Selección del formato de presentación

Se optó por una presentación tipo Blog que separe la visual según relevancia del información, distinguiendo la presentación general, de la construcción teórica y los productos.

### Selección de herramientas de trabajo

A partir de los requerimientos antes mencionados se consideró como herramienta principal el sowftware (Entorno de Desarrollo Integrado) Rstudio, que permite a partir del lenguaje de programación R, el analisis y visualización de inforamción: datos estadisticos, datos geográficos y visualizaciones en formato web (Distill). 

De forma complementaria para la importación y procesamiento de algunos datos se trabajó con QGis. 

Y para el alojamiento de la información se propiciaron plataformas online como Github y google Drive.

### Análisis de Datos

#### Data Ingestión | Importación de los datos

Se investigaron múltiples opciones de importación y procesamiento de la información en función de la compatibilidad de las herramientas con los servidores que alojaban los datos y el tamaño de los mismos.

1 - Organización del almacenamiento de datos: Creación del Proyecto de Rstudio alojado en el ordenador y vinculado al repositorios Github, Creación del Blog utilizando la herramienta Distill definiendo la estructura de los datos del Blog, creación de un sitio en Google Drive para el almacenamiento de las capas finales, e Identificación de una carpeta de cache, donde procesar la información temporal.

2 - Importación de los datos

Para límites jurisdiccionales: Rstudio (Serivicio WFS).

Para el Parcelario: QGis (Serivicio WFS).

Edificabilidad: Descarga Online y procesamiento con Rstudio.

Estructura Vial: Rstudio (Serivicio OSM)

Aménidades urbanas: Rstudio (Serivicio OSM)

#### Data Wrangling | Limpieza de los datos

A partir de múltiples ensayos con la información se definió una metodología en torno a las unidades municipales, que establezan:

A - Una visualización estática sobre un rectángulo de coordenadas geoespaciales de vista online.
B - Una visualización estática sobre un rectángulo de coordenadas de descarga en PDF tamaño A3, de vista online y accesible en una presentación en papel (escala a definir para cada municipio)
B - Una visualización dinámica sobre la unidad municipal, vista online.
C - Dataset de información ordenada recopilada para cada municipio.

Para los datos parcelarios, ya que los mísmos no se podían importar de forma correcta en Rstudio, ni completa en Qgis, se descargaron parcialmente con Qgis y se limpiaron en Rstudio, para obtener las intersecciones relevantes a la unidad de análisis.

Para los datos de edificacion, se realizó la descarga correspondiente y su reducción para su procesamiento en Rstudio, donde luego se procedío a realizar las intersecciones relevantes a la unidad de análisis.

Para los demás elementos: el Recorte de las unidades territoriales, los límites jurisdiccionales y los objetos OMS (Calles y Amenidades), se utilizaron códigos de Rstudio, que permitieron la importación y el procesamiento de los datos en las intersecciones relevantes a la unidad de análisis. 

#### Data Visualization | Presentación de los datos

Toda la información procesada se cargó al Drive y relinkeó a los codigos correspondientes de la estructura de datos del Proyecto (Distill) donde se customizó para la vista correspondiente del Blog.

## Desafios y Hallazgos

Prueba y error :V 











